### ISSUE TITLE
需求规格说明书-状态图 运行开发环境

### ISSUE THREAD

**Issue by Yzx835** [sebuaa2020/Team208#2]
- [x] 完善状态图
- [x] 运行与开发环境加入启智ROS相关介绍

**Comment by fjhzhixi** [comment]
根据评审反馈意见完成：

1. 对于功能需求中的状态图修改在选择分支处的错误

**Comment by fjhzhixi** [comment]
根据评审中的意见完成如下修改：

1. 对于功能需求中的状态图修改在选择分支处的错误
2. 对于系统运行和开发的软硬件环境进一步明确
3. 对于功能需求增加更详细的文字描述
