### ISSUE TITLE
Coding-TargetGrab

### ISSUE THREAD

**Issue by Yzx835** [sebuaa2020/Team208#29]

**Comment by LidaGuo1999** [comment]
已完成目标检测模块的核心功能，测试尚未完全。

**Comment by LidaGuo1999** [comment]
目标抓取功能由于模拟器限制，现暂不进行开发，主要测试目标检测模块的功能是否正确。

**Comment by LidaGuo1999** [comment]
目标检测功能利用自制的world文件测试完成，对于桌子高度在0.6-1.5米的桌面上的物体可有效检测。
