### ISSUE TITLE
Doc-SDD 详细设计修改

### ISSUE THREAD

**Issue by Yzx835** [sebuaa2020/Team208#35]
根据目前的开发进度，对设计文档详细设计部分进行修改
- [x] GUI部分
- [x] 主动控制
- [x] 导航模块
- [x] 目标检测模块
- [x] 对文档其他部分进行适配

**Comment by fjhzhixi** [comment]
对详细设计中的导航模块进行修改

**Comment by DoubleRider** [comment]
对用户接口和软件环境部分进行了修改，暂时缺少目标检测与抓取部分的界面图，将在完成界面与目标检测模块连接后补充。

**Comment by LidaGuo1999** [comment]
对目标检测模块的详细设计进行更新，与最新的代码保持匹配。

**Comment by Yzx835** [comment]
详细设计部分已基本修改完毕，待后续审核
